services:
  backend:
    build: ./back-end
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
